--- #YAML:1.0
name:                B-Deobfuscate
version:             0.18
abstract:            Deobfuscate source code
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    B::Keywords:                   1.04
    YAML:                          0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Joshua ben Jore <jjore@cpan.org>
