#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         B-Deobfuscate
version:      0.08
version_from: lib/B/Deobfuscate.pm
installdirs:  site
requires:
    YAML:                          0
    B::Keywords:                   0.03

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_07
